version: 0.0
os: linux
#files:
#   - source: target/LoginWebApp.war 
#     destination: /usr/share/tomcat6/webapps
#permissions:
#   - object: /usr/share/tomcat6/webapps
#     pattern: "**"
#     owner: tomcat
#     group: tomcat
#     mode: 755
#     type:
#       - file
hooks:
   BeforeInstall:
    - location: scripts/instlltomcat.sh
      runas: root
    - location: scripts/starttomcat.sh
      runas: root
   AfterInstall:
    - location: scripts/restarttomcat.sh
      runas: root
